### ISSUE TITLE
[BUG] Version incompatibility with CallHandler arguments

### ISSUE THREAD

**Issue by Enjay001** [ZDoom/gzdoom#3412]
### GZDoom version

GZDoom 4.12.2 vs recent Git builds

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I'm not sure if this will be of interest or not, because it seems like the result of a deliberate change.  However, I am aware of it affecting one mod "in the wild" - though that mod has since been updated to work with 4.14.3+

It was mentioned on the forum, but I don't think it ever made it to a bug report.  I did also report it on UZDoom and a fix has been applied there.  I don' know if the fix is appropriate/desirable for GZDoom or not.

Here's the report much as submitted to UZDoom:

In 4.14.2, if you run a ZScript mod that uses CallHandler, you have to provide arguments. e.g.
`CallHandler(Handler);`
If you just write:
`CallHandler();`
GZDoom refuses to start the game saying:
`Insufficient arguments in call to CallHandler`

However, things were updated so that CallHandler no longer takes an argument. So, in a recent build of GZDoom, if you write:
`CallHandler(Handler);`
which was required for 4.14.2 you get told:
`Too many arguments in call to CallHandler`
and the code has to be changed to
`CallHandler();`
which is, of course, unacceptable to 4.14.2.

The only mod I am aware of where was a problem is [Rise of the Triad-style Message Boxes](https://forum.zdoom.org/viewtopic.php?style=14&p=1001173#p1001173) by AFADoomer.

I raised the issue in that thread and AFADoomer has modified his code to be compatible with current builds of the engine. So, as far as the mod is concerned, the issue is effectively over. Though, as a result, the mod no longer works on the current release version of GZDoom.

I just wanted to raise it just in case it has implications elsewhere. AFADoomer's ZSCript file is versioned to 4.2. So I'm surprised that a change in GZDoom version breaks the mod because I thought the reason to version a ZScript file was so that GZDoom would parse the file as it it was the version specified, and the version specified in the file would have required an argument for CallHandler. Maybe I misunderstood?

Anyway here's what was done to address it for UZDoom:
https://github.com/UZDoom/UZDoom/pull/232

That links to the issue that I raised (234) which is basically the same as this one, but it also says that it fixes another issue (38) which may also be relevant to GZDoom, or may just be a better/more technical explanation of what I described.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load AFADoomer's Rise of the Triad-style Message Boxes in GZDoom official and any recent build of GZdoom
2. The mod will work in recent builds, but not in GZDoom official
3. Restore the old code (swapping `CallHandler();` for `CallHandler(Handler);` on line 209 of the zscript file for the mod.
4. The situation will now be reversed, the mod will work on GZDoom official, but not in recent builds.

### Your configuration

```ini

```
